/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedK3lWasteMonitoringRouteImport } from './routes/_authenticated/k3l.waste-monitoring'
import { Route as AuthenticatedGaVehicleMonitoringRouteImport } from './routes/_authenticated/ga.vehicle-monitoring'
import { Route as AuthenticatedFmsUtilityTestsRouteImport } from './routes/_authenticated/fms.utility-tests'
import { Route as AuthenticatedFmsSparePartsRouteImport } from './routes/_authenticated/fms.spare-parts'
import { Route as AuthenticatedFmsPreventiveMaintenanceRouteImport } from './routes/_authenticated/fms.preventive-maintenance'
import { Route as AuthenticatedFmsEquipmentHistoryRouteImport } from './routes/_authenticated/fms.equipment-history'
import { Route as AuthenticatedFmsDailyChecklistRouteImport } from './routes/_authenticated/fms.daily-checklist'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedK3lWasteMonitoringRoute =
  AuthenticatedK3lWasteMonitoringRouteImport.update({
    id: '/k3l/waste-monitoring',
    path: '/k3l/waste-monitoring',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGaVehicleMonitoringRoute =
  AuthenticatedGaVehicleMonitoringRouteImport.update({
    id: '/ga/vehicle-monitoring',
    path: '/ga/vehicle-monitoring',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFmsUtilityTestsRoute =
  AuthenticatedFmsUtilityTestsRouteImport.update({
    id: '/fms/utility-tests',
    path: '/fms/utility-tests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFmsSparePartsRoute =
  AuthenticatedFmsSparePartsRouteImport.update({
    id: '/fms/spare-parts',
    path: '/fms/spare-parts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFmsPreventiveMaintenanceRoute =
  AuthenticatedFmsPreventiveMaintenanceRouteImport.update({
    id: '/fms/preventive-maintenance',
    path: '/fms/preventive-maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFmsEquipmentHistoryRoute =
  AuthenticatedFmsEquipmentHistoryRouteImport.update({
    id: '/fms/equipment-history',
    path: '/fms/equipment-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFmsDailyChecklistRoute =
  AuthenticatedFmsDailyChecklistRouteImport.update({
    id: '/fms/daily-checklist',
    path: '/fms/daily-checklist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fms/daily-checklist': typeof AuthenticatedFmsDailyChecklistRoute
  '/fms/equipment-history': typeof AuthenticatedFmsEquipmentHistoryRoute
  '/fms/preventive-maintenance': typeof AuthenticatedFmsPreventiveMaintenanceRoute
  '/fms/spare-parts': typeof AuthenticatedFmsSparePartsRoute
  '/fms/utility-tests': typeof AuthenticatedFmsUtilityTestsRoute
  '/ga/vehicle-monitoring': typeof AuthenticatedGaVehicleMonitoringRoute
  '/k3l/waste-monitoring': typeof AuthenticatedK3lWasteMonitoringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fms/daily-checklist': typeof AuthenticatedFmsDailyChecklistRoute
  '/fms/equipment-history': typeof AuthenticatedFmsEquipmentHistoryRoute
  '/fms/preventive-maintenance': typeof AuthenticatedFmsPreventiveMaintenanceRoute
  '/fms/spare-parts': typeof AuthenticatedFmsSparePartsRoute
  '/fms/utility-tests': typeof AuthenticatedFmsUtilityTestsRoute
  '/ga/vehicle-monitoring': typeof AuthenticatedGaVehicleMonitoringRoute
  '/k3l/waste-monitoring': typeof AuthenticatedK3lWasteMonitoringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fms/daily-checklist': typeof AuthenticatedFmsDailyChecklistRoute
  '/_authenticated/fms/equipment-history': typeof AuthenticatedFmsEquipmentHistoryRoute
  '/_authenticated/fms/preventive-maintenance': typeof AuthenticatedFmsPreventiveMaintenanceRoute
  '/_authenticated/fms/spare-parts': typeof AuthenticatedFmsSparePartsRoute
  '/_authenticated/fms/utility-tests': typeof AuthenticatedFmsUtilityTestsRoute
  '/_authenticated/ga/vehicle-monitoring': typeof AuthenticatedGaVehicleMonitoringRoute
  '/_authenticated/k3l/waste-monitoring': typeof AuthenticatedK3lWasteMonitoringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/fms/daily-checklist'
    | '/fms/equipment-history'
    | '/fms/preventive-maintenance'
    | '/fms/spare-parts'
    | '/fms/utility-tests'
    | '/ga/vehicle-monitoring'
    | '/k3l/waste-monitoring'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/fms/daily-checklist'
    | '/fms/equipment-history'
    | '/fms/preventive-maintenance'
    | '/fms/spare-parts'
    | '/fms/utility-tests'
    | '/ga/vehicle-monitoring'
    | '/k3l/waste-monitoring'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/fms/daily-checklist'
    | '/_authenticated/fms/equipment-history'
    | '/_authenticated/fms/preventive-maintenance'
    | '/_authenticated/fms/spare-parts'
    | '/_authenticated/fms/utility-tests'
    | '/_authenticated/ga/vehicle-monitoring'
    | '/_authenticated/k3l/waste-monitoring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/k3l/waste-monitoring': {
      id: '/_authenticated/k3l/waste-monitoring'
      path: '/k3l/waste-monitoring'
      fullPath: '/k3l/waste-monitoring'
      preLoaderRoute: typeof AuthenticatedK3lWasteMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ga/vehicle-monitoring': {
      id: '/_authenticated/ga/vehicle-monitoring'
      path: '/ga/vehicle-monitoring'
      fullPath: '/ga/vehicle-monitoring'
      preLoaderRoute: typeof AuthenticatedGaVehicleMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fms/utility-tests': {
      id: '/_authenticated/fms/utility-tests'
      path: '/fms/utility-tests'
      fullPath: '/fms/utility-tests'
      preLoaderRoute: typeof AuthenticatedFmsUtilityTestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fms/spare-parts': {
      id: '/_authenticated/fms/spare-parts'
      path: '/fms/spare-parts'
      fullPath: '/fms/spare-parts'
      preLoaderRoute: typeof AuthenticatedFmsSparePartsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fms/preventive-maintenance': {
      id: '/_authenticated/fms/preventive-maintenance'
      path: '/fms/preventive-maintenance'
      fullPath: '/fms/preventive-maintenance'
      preLoaderRoute: typeof AuthenticatedFmsPreventiveMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fms/equipment-history': {
      id: '/_authenticated/fms/equipment-history'
      path: '/fms/equipment-history'
      fullPath: '/fms/equipment-history'
      preLoaderRoute: typeof AuthenticatedFmsEquipmentHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fms/daily-checklist': {
      id: '/_authenticated/fms/daily-checklist'
      path: '/fms/daily-checklist'
      fullPath: '/fms/daily-checklist'
      preLoaderRoute: typeof AuthenticatedFmsDailyChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFmsDailyChecklistRoute: typeof AuthenticatedFmsDailyChecklistRoute
  AuthenticatedFmsEquipmentHistoryRoute: typeof AuthenticatedFmsEquipmentHistoryRoute
  AuthenticatedFmsPreventiveMaintenanceRoute: typeof AuthenticatedFmsPreventiveMaintenanceRoute
  AuthenticatedFmsSparePartsRoute: typeof AuthenticatedFmsSparePartsRoute
  AuthenticatedFmsUtilityTestsRoute: typeof AuthenticatedFmsUtilityTestsRoute
  AuthenticatedGaVehicleMonitoringRoute: typeof AuthenticatedGaVehicleMonitoringRoute
  AuthenticatedK3lWasteMonitoringRoute: typeof AuthenticatedK3lWasteMonitoringRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFmsDailyChecklistRoute: AuthenticatedFmsDailyChecklistRoute,
  AuthenticatedFmsEquipmentHistoryRoute: AuthenticatedFmsEquipmentHistoryRoute,
  AuthenticatedFmsPreventiveMaintenanceRoute:
    AuthenticatedFmsPreventiveMaintenanceRoute,
  AuthenticatedFmsSparePartsRoute: AuthenticatedFmsSparePartsRoute,
  AuthenticatedFmsUtilityTestsRoute: AuthenticatedFmsUtilityTestsRoute,
  AuthenticatedGaVehicleMonitoringRoute: AuthenticatedGaVehicleMonitoringRoute,
  AuthenticatedK3lWasteMonitoringRoute: AuthenticatedK3lWasteMonitoringRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
